# https://byrdwell.com/Triacylglycerols/FattyAcids.htm

c4 =
    .common = Butyric
    .systematic = butanoic
c5 =
    .common = Valeric
    .systematic = pentanoic
c6 =
    .common = Caproic
    .systematic = hexanoic
c7 =
    .common = Enanthic
    .systematic = heptanoic
c8 =
    .common = Caprylic
    .systematic = octanoic
c9 =
    .common = Pelargonic
    .systematic = nonanoic
c10 =
    .common = Capric
    .systematic = decanoic
c11 =
    .common = Undecylic
    .systematic = hendecanoic
c12 =
    .common = Lauric
    .systematic = dodecanoic
c13 =
    .common = Tridecylic
    .systematic = tridecanoic
c14 =
    .common = Myristic
    .systematic = tetradecanoic
c15 =
    .common = Pentadecylic
    .systematic = pentadecanoic
c16 =
    .common = Palmitic
    .systematic = hexadecanoic
c16c7 =
    .common = Hypogeic
    .systematic = (Z)-hexadec-7-enoic
c16c9 =
    .common = Palmitoleic
    .systematic = c-9-Hexadecenoic
c16t9 =
    .common = Palmitelaidic
    .systematic = t-9-Hexadecenoic
c16c11 =
    .common = Palmitvaccenic
    .systematic = (Z)-hexadec-11-enoic
c16c7c10 =
    .systematic = (Z,Z)-hexadeca-7,10-dienoic
c16c7c10c13 =
    .common = Roughanic
    .systematic = (Z,Z,Z)-hexadeca-7,10,13-trienoic
c16c4c7c10c13 =
    .systematic = (Z,Z,Z,Z)-hexadeca-4,7,10,13-tetraenoic
c17 =
    .common = Margaric
    .systematic = heptadecanoic
c18 =
    .common = Stearic
    .systematic = octadecanoic
c18c9 =
    .common = Oleic
    .systematic = (Z)-octadec-9-enoic
c18t9 =
    .common = Elaidic
    .systematic = (E)-octadec-9-enoic
c18c11 =
    .common = Asclepic
    .systematic = (Z)-octadec-11-enoic
c18c6c9 =
    .common = γ-Linoleic
    .systematic = c-9,12-Octadecadienoic
c18c9c12 =
    .common = Linoleic
    .systematic = c-9,12-Octadecadienoic
c18c9c12c15 =
    .common = α-Linolenic
    .systematic = c-9,12,15-Octadec-trienoic
c18c6c9c12 =
    .common = γ-Linolenic
    .systematic = c-6,9,12-Octadec-trienoic
c18c9t11t13 =
    .common = α-Eleostearic
    .systematic = 9c,11t,13t-Octadec-trienoic
c18t9t11t13 =
    .common = β-Eleostearic
    .systematic = 9t,11t,13t-Octadec-trienoic
c18c8t10c12 =
    .common = Jacaric
    .systematic = 8c,10t,12c-Octadec-trienoic
c18t9t11c13 =
    .common = Catalpic
    .systematic = 9t,11t,13c-Octadec-trienoic
c18c6c9c12c15 =
    .common = Stearidonic
    .systematic = c-6,9,12,15-Octadec-tetraenoic
c19 =
    .common = Nonadecylic
    .systematic = nonadecanoic
c20 =
    .common = Arachidic
    .systematic = eicosanoic
c20c9 =
    .common = Gadoleic
    .systematic = c-9-Eicosenoic
c20c11 =
    .common = Gondoic
    .systematic = c-11-Eicosenoic
c20c13 =
    .common = Paullinic
    .systematic = (Z)-icos-13-enoic
c20c11c14 =
    .common = DihomoLinoleic
    .systematic = c-11,14-Eicosadienoic
c20c11c14c17 =
    .common = Bis-homo-α-Linolenic, ETA
    .systematic = c-11,14,17-Eicos-trienoic
c20c8c11c14 =
    .common = Bis-homo-γ-Linolenic
    .systematic = c-8,11,14-Eicos-trienoic
c20c5c8c11 =
    .common = Mead
    .systematic = c-5,8,11-Eicos-trienoic
c20c5c8c11c14 =
    .common = Arachidonic
    .systematic = c-5,8,11,14-Eicos-tetraenoic
c20c8c11c14c17 =
    .common = Eicos-tetraenoic
    .systematic = c-8,11,14,17-Eicos-tetraenoic
c20c5c8c11c14c17 =
    .common = EPA
    .systematic = c-5,8,11,14,17-Eicos-pentaenoic
c21 =
    .common = Heneicosylic
    .systematic = heneicosanoic
c22 =
    .common = Behenic
    .systematic = docosanoic
c22c13 =
    .common = Erucic
    .systematic = c-13-docos-enoic
c22c15 =
    .systematic = (Z)-docos-15-enoic
c22c13c16 =
    .common = docos-adienoic
    .systematic = (Z,Z)-docos-13,16-dienoic
c22c5c13c16 =
    .common = Eranthic
    .systematic = c-5,13,16-docos-trienoic
c22c7c10c13c16 =
    .common = Adrenic
    .systematic = c-7,10,13,16-docos-tetraenoic
c22c7c10c13c16c19 =
    .common = DPA
    .systematic = c-7,10,13,16,19-docos-pentaenoic
c22c4c7c10c13c16c19 =
    .common = DHA
    .systematic = c-4,7,10,13,16,19-docos-hexaenoic
c23 =
    .common = Tricosylic
    .systematic = tricosanoic
c24 =
    .common = Lignoceric
    .systematic = tetracosanoic
c24c15 =
    .common = Nervonic
    .systematic = c-15-Tetracosenoic
c24c15c18 =
    .common = Tetracosadienoic
    .systematic = c-15,18-Tetracosadienoic
c24c12c15c18 =
    .common = Tetracosatrienylic
    .systematic = c-12,15,18-Tetracos-trienoic
c24c9c12c15c18 =
    .common = Tetracosatetraenylic
    .systematic = c-9,12,15,18-Tetracos-tetraenoic
c24c6c9c12c15c18 =
    .common = Tetracosapentaenylic
    .systematic = c-6,9,12,15,18-Tetracosapentaenoic
c24c6c9c12c15c18c21 =
    .common = Tetracosahexaenylic
    .systematic = c-6,9,12,15,18,21-Tetracosahexaenoic
c25 =
    .common = Hyenic
    .systematic = pentacosanoic
c26 =
    .common = Cerotic
    .systematic = hexacosanoic
c26c17 =
    .common = Ximenic
    .systematic = c-17-Hexacosenoic
c26u0u0 =
    .common = Hexacosadienylic
    .systematic = hexacosadienoic
c26u0u0u0 =
    .common = Hexacosatrienylic
    .systematic = hexacos-trienoic
c26u0u0u0u0 =
    .common = Hexacosatetraenylic
    .systematic = hexacos-tetraenoic
c26u0u0u0u0u0 =
    .common = Hexacosapentaenylic
    .systematic = hexacosapentaenoic
c26u0u0u0u0u0u0 =
    .common = Hexacosahexaenylic
    .systematic = hexacosahexaenoic
c27 =
    .common = Carboceric
    .systematic = heptacosanoic
c28 =
    .common = Montanic
    .systematic = octacosanoic
c28u0 =
    .common = Octacosenylic
    .systematic = octacosenoic
c28u0u0 =
    .systematic = octacosadienoic
c29 =
    .common = Nonacosylic
    .systematic = nonacosanoic
c30 =
    .common = Melissic
    .systematic = triacontanoic
c30c21 =
    .common = Lumequeic
    .systematic = c-21-Triacontenoic
c31 =
    .common = Henatriacontylic
    .systematic = henatriacontanoic
c32 =
    .common = Lacceroic
    .systematic = dotriacontanoic
c32u0 =
    .common = Dotriacontenylic
    .systematic = dotriacontenoic
c32u0u0 =
    .systematic = dotriacontadienoic
c33 =
    .common = Psyllic
    .systematic = triatriacontanoic
c34 =
    .common = Gheddic
    .systematic = tetratriacontanoic
c34u0 =
    .common = Tetratriacontenylic
    .systematic = tetratriacontenoic
c34u0u0 =
    .systematic = tetratriacontadienoic
c35 =
    .common = Ceroplastic
    .systematic = pentatriacontanoic
c36 =
    .common = Hexatriacontylic
    .systematic = hexatriacontanoic
c36u0 =
    .common = Hexatriacontenylic
    .systematic = hexatriacontenoic
c36u0u0 = =
    .systematic = hexatriacontadienoic